# Generated by Django 5.0.7 on 2024-09-24 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_management', '0001_initial'),
        ('patient_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmanagement',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient_management.appointment'),
        ),
    ]
