# Generated by Django 5.0.7 on 2024-09-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(0, 'User'), (1, 'Admin'), (2, 'Doctor')], max_length=20),
        ),
    ]
