# Generated by Django 5.0.7 on 2024-09-24 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docter_management', '0001_initial'),
        ('patient_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eprescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patient_management.patient'),
        ),
    ]
