# Generated by Django 5.0.7 on 2024-09-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0002_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Scheduled'), (1, 'Cancelled'), (2, 'Completed')]),
        ),
    ]
